#!/bin/bash

# todo
# -p, print raw text representation of database
# -a, add entry to database
# -r <string>, remove entry if type supports remove (below):
#	dict, remove by key

DPATH="/var/simpledb"
CPATH="config"
CURRENT="current.conf"

usage() {
	echo "$0:"
	echo "    -h - display help screen"
	echo "    -c <type> <name> - create a new database, name, with one of the following types:"
	echo "                    -dict - key value pair database"
	echo "                    -log - raw text as written"
	echo "    -s <name> - set the database name to the current database"
	echo "    -d <name> - delete database name"
	echo "    -q - suppress output"
	exit 0
}

create_db() {
	type=$1
	dname=$2
	echo "creating database $dname using type $type"
	mkdir -p $DPATH
	touch $DPATH/$dname
	echo "name: $dname" >> $DPATH/$dname
	echo "type: $type" >> $DPATH/$dname
	echo "" >> $DPATH/$dname
	echo "database created"
}

delete_db() {
	dname=$1
	echo "deleting database $dname"
	curdb=$(head -1 $DPATH/$dname | cut -d ' ' -f2)
	if [ "$curdb" == "$dname" ]; then
		_delete_current
	fi
	rm -f $DPATH/$dname
	echo "database deleted"
}

_delete_current() {
	if [ -f $DPATH/$CPATH/$CURRENT ]; then
		rm -f $DPATH/$CPATH/$CURRENT
	fi
}

set_db() {
	dname=$1
	if [ ! -d $DPATH/$CPATH ]; then
		mkdir -p $DPATH/$CPATH
	fi
	_delete_current
	head -2 $DPATH/$dname > $DPATH/$CPATH/$CURRENT
}

suppress_output() {
	exec 1>/dev/null
	exec 2>&1
}

list_dbs() {
	for file in $DPATH/*
	do
		if [ ! -f $file ]; then
			continue
		fi
		name=$(basename $file)
		echo "$name"
	done
}

while (($#)) 
do
	case $1 in
		"-h")
			usage
			;;
		"-c")
                        shift
			type=$1
			shift
			dname=$1
			if [ -z $type ]; then
				echo "type not provided for -c arg"
				exit 1
			fi
			if [ -z $dname ]; then
				echo "name not provided for -c arg"
				exit 2
			fi
			if [ -f $DPATH/$dname ]; then
				echo "database already exists"
				exit 3
			fi
			if [ "$type" != "dict" ] && \
			   [ "$type" != "log" ]; then
				echo "given type does not match a known type"
				exit 4
			fi
			create_db $type $dname
			;;
		"-d")
			shift
			dname=$1
			if [ ! -f $DPATH/$dname ]; then
				echo "database does not exist"
				exit 5
			fi
			delete_db $dname
			;;
		"-s")
			shift
			dname=$1
			if [ ! -f $DPATH/$dname ]; then
				echo "database does not exist"
				exit 6
			fi
			set_db $dname
			;;
		"-q")
			suppress_output
			;;
		"-l")
			list_dbs
			;;
		*)
			echo "unknown arg: $1"
			;;
	esac
	shift
done

